name: release-aman
on:
  workflow_dispatch:
    inputs:
      tags:
        required: true
        description: "version (e.g.: 1.5.2)"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Add tag
        run: |
          git tag v${{ github.event.inputs.tags }}
          PUSHURL="https://${GITHUB_ACTOR}:${{ github.token }}@github.com/${GITHUB_REPOSITORY}"
          git push ${PUSHURL} v${{ github.event.inputs.tags }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install \
            gcc libc6-dev \
            libx11-dev xorg-dev libxtst-dev libpng++-dev \
            xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev \
            libxkbcommon-dev \
            xsel xclip \
            gobjc++
      - name: OSXCross for CGO Support
        run: |
          mkdir /home/runner/work/osxcross
          git clone https://github.com/plentico/osxcross-target.git /home/runner/work/osxcross/target
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --config .github/workflows/.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
